"""
LLM Response Generation via NVIDIA NIM (Llama 3.1 405B Instruct)
─────────────────────────────────────────────────────────────────
Replaces hard-coded template text in build_genuine_response() with a
fluid, context-aware reply generated by the LLM.

The existing NLP pipeline (intent, sentiment, DB lookup) still runs
in full — this module only handles the final text generation step.
All DB values are passed verbatim so the model cannot hallucinate them.
"""

import os
import json
import logging

logger = logging.getLogger(__name__)

_client = None


def _get_client():
    global _client
    if _client is None:
        from openai import OpenAI  # lazy import — only loaded when needed
        api_key = os.getenv("NVIDIA_API_KEY")
        if not api_key:
            raise ValueError("NVIDIA_API_KEY is not set in environment")
        _client = OpenAI(
            base_url="https://integrate.api.nvidia.com/v1",
            api_key=api_key,
        )
    return _client


def generate_response(
    user_message: str,
    intent: dict,
    sentiment: dict,
    db_ctx: dict,
    template_text: str,
    context: str = "",
) -> str:
    """
    Generate a natural language response using Llama 3.1 405B.

    Parameters
    ----------
    user_message   : raw customer message
    intent         : output of classify_intent()
    sentiment      : output of analyze_sentiment()
    db_ctx         : output of gather_db_context() — verified DB records
    template_text  : the template-generated response (used as a grounding
                     hint so the LLM knows which data points to include)
    context        : recent session history (last ~20 turns)

    Returns
    -------
    str — the LLM-generated response text, or the template_text on failure
    """
    # ── Build the DB data section ──────────────────────────────────────────
    if db_ctx.get("found") and db_ctx.get("entities"):
        db_section = (
            "\n\nVERIFIED DATABASE RECORDS"
            " (use these exact values — do NOT invent or modify IDs, amounts, or dates):\n"
            + json.dumps(db_ctx["entities"], indent=2, default=str)
        )
    elif db_ctx.get("errors"):
        db_section = (
            "\n\nDATABASE LOOKUP ERRORS: " + "; ".join(db_ctx["errors"])
        )
    else:
        db_section = ""

    # ── Recent conversation history ────────────────────────────────────────
    history_section = (
        f"\n\nRECENT CONVERSATION HISTORY:\n{context[-1500:]}" if context else ""
    )

    # ── Empathy instruction ────────────────────────────────────────────────
    empathy_note = ""
    if sentiment.get("label") == "negative" and sentiment.get("intensity", 0) > 0.35:
        empathy_note = (
            "\nThe customer appears frustrated — open your reply with a brief, "
            "sincere apology before addressing their issue."
        )

    # ── System prompt ─────────────────────────────────────────────────────
    system_prompt = f"""You are a helpful, professional customer support assistant for an e-commerce platform.
Your goal is to resolve the customer's issue clearly and concisely.

STRICT RULES:
- Use ONLY the database records provided below — never invent order IDs, amounts, tracking numbers, or dates.
- If database records are available, reference their exact values in your reply.
- If no records are available, ask the customer for their order ID (e.g. ORD-100001) or customer ID (e.g. CUST-001001).
- Reply in plain, conversational prose — no bullet points, no markdown formatting.
- Keep replies to 2–4 sentences unless the situation genuinely requires more detail.
- Do not repeat the customer's question back to them.{empathy_note}

DETECTED INTENT: {intent.get('primary_intent', 'unknown')}
CUSTOMER SENTIMENT: {sentiment.get('label', 'neutral')} (intensity {sentiment.get('intensity', 0):.0%}){db_section}{history_section}

REFERENCE ANSWER (grounding — rephrase naturally, keep all data points accurate):
{template_text}"""

    # ── Call the model ─────────────────────────────────────────────────────
    client = _get_client()
    completion = client.chat.completions.create(
        model="meta/llama-3.1-405b-instruct",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=0.4,   # low temp keeps factual answers grounded
        max_tokens=350,
        timeout=20,
    )
    return completion.choices[0].message.content.strip()

